spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/digitalBank"
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
    jpa:
      database: POSTGRESQL
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: create

aws:
  access_key_id:
  secret_access_key: 

s3:
  bucket: digital-bank
  region: sa-east-1